### ISSUE TITLE
Emulator Datastore Viewer

### ISSUE THREAD

**Issue by mitchhentges** [googleapis/google-cloud-datastore#148]
I'm currently migrating from the Google App Engine development environment to a more discrete environment, using the Client Datastore API to manage data. When developing with App Engine, I would be able to start a "Devserver", which would run my app's `war` file and provide helpful tooling, like the Datastore Viewer:

![2016-10-03-162356_1716x282_scrot](https://cloud.githubusercontent.com/assets/7784737/19057620/0fd1d0a6-8986-11e6-8a4e-82326741001e.png)

Does Google Cloud's Datastore Emulator provide a Datastore Viewer? If not, then this is a feature request :smile:

**Comment by stran12** [comment]
I would also really like this feature 👍

**Comment by iamacarpet** [comment]
+1 for us too.

**Comment by MichalFikejs** [comment]
+1 for us as well.

**Comment by gcoyne** [comment]
+1 for me as well

**Comment by amirshenhav** [comment]
+1 as well

**Comment by onluiz** [comment]
+1 as well

**Comment by pushkar** [comment]
+1

**Comment by shauvik** [comment]
+1

**Comment by mdevalk** [comment]
+1

**Comment by atali** [comment]
any update on this ? it would be very useful

**Comment by wsh** [comment]
Hey--no update yet that I can provide but looking into it. :)

Will

**Comment by ramesh-dev** [comment]
+1

**Comment by ahmadmuzakki29** [comment]
+1

**Comment by calsmith** [comment]
+1 for PHP

**Comment by artemgavrilov** [comment]
+1

**Comment by atali** [comment]
+1

**Comment by mitchhentges** [comment]
Hey lads, I appreciate the enthusiasm, and I'm glad we're all hopeful for this feature, but it'd be :100: if we used the GitHub feature to add a :+1: (or whatever) to an existing message, rather than adding a new comment with just "+1" for the text.

I keep getting excited whenever I get an email notification for this thread, but it's always "+1" comments, which is a little less exciting :wink:

**Comment by jouerose** [comment]
+1

**Comment by wannamit** [comment]
+1... would really be helpful

**Comment by tonyno** [comment]
+1

**Comment by TomerG2** [comment]
+1

**Comment by azk** [comment]
+1

**Comment by nicolasmendoza** [comment]
+1

**Comment by firstthumb** [comment]
+1

**Comment by chrisbbe** [comment]
+1

**Comment by enyo** [comment]
Is there any update on this? It's now 1,5 years that we have to develop without a way to see the data in our database. How is this not top priority??

**Comment by ekhaidarov** [comment]
I agree it would be great to get a basic rudimentary tool to be able to query against local datastore.

**Comment by jreim** [comment]
Tosses +1 on the pile.

**Comment by martflu** [comment]
+1

**Comment by ramybenaroya** [comment]
Hey all, We wrote [@streamrai/dsui](https://github.com/streamrail/dsui) at [Streamrail](https://github.com/streamrail).   
This is a very basic UI for datastore emulator (read only)
It also includes a search by `Id` and `Name` properties due to the way we define models. So, it might not fit everyone's needs perfectly, but it's worth a shot.

**Comment by enyo** [comment]
Thanks @ramybenaroya but when I try to install, I get a `404`:

```bash
[enyo:~] $ npm i -g @streamrail/dsui
npm ERR! code E404
npm ERR! 404 Not Found: @streamrail/dsui@latest
```

**Comment by GabiAxel** [comment]
Greetings. I also wrote a tool for this: https://github.com/GabiAxel/google-cloud-gui

It allows connecting to multiple projects in emulator and production, browse namespaces, kinds and entities, and delete entities (the functionality that exists in GAE devserver).

You are welcome to give it a try and send feedback.

**Comment by mistriel** [comment]
+1 Would be very helpful

**Comment by QuantumInformation** [comment]
I tries this but couldn't get it to work to see the data: https://github.com/streamrail/dsui/issues/3#issuecomment-536057973

**Comment by QuantumInformation** [comment]
Just tried it, works a treat!

**Comment by abhaystoic** [comment]
+1 Would be very helpful

**Comment by nicklefors** [comment]
+1

**Comment by twais** [comment]
+1

**Comment by utkarshshende2596** [comment]
+1

**Comment by jainkunal** [comment]
+1

**Comment by UsamaAmjad** [comment]
+1

**Comment by DevDevious** [comment]
+1

**Comment by saifali40** [comment]
+1

**Comment by remko** [comment]
Unfortunately, I had various (fundamental) issues with all of the existing GUIs I tried, and/or was missing crucial features, so I created one that tries to address these problems: https://github.com/remko/dsadmin . This one supports (graphical) editing, entity/property creation/deletion, large datasets, and also comes in a self-contained native binary.

**Comment by a1c-rwilliamson** [comment]
+1

**Comment by jimblackler** [comment]
Any update? Seems like core functionality.

**Comment by hraban** [comment]
I don't have the required tools locally to test this (anymore), but I see someone posted a way to do this at "https://stackoverflow.com/a/70897628/4359699".

Is that a resolution for this specific issue?

**Comment by remko** [comment]
@hraban This seems to rely on the Java dev_appserver, which only works if you use a legacy AppServer app written in Java. This does not cover AppEngine apps written in another language (e.g. Python) or apps for recent runtimes (which do not use any dev_appserver at all). 

FWIW, I don't think there will ever be a built-in UI again. From what I can see, Datastore has gone in maintenance mode, and new code is only going into the newer DB technologies. Since you can get a UI using third party software, I doubt a pressing need is felt. But it would still be nice if this was officially acknowledged, so this issue can be closed.

**Comment by kk2211** [comment]
+1

**Comment by meredithslota** [comment]
Hi folks — there's a companion open feature request in our public issue tracker (https://b.corp.google.com/issues/229824394) for a Firestore (which would likely include Firestore in Datastore mode, but possibly not Datastore itself, TBD) viewer. I'm going to close this issue in favor of that one, since that one is getting reviewed by the product team. I invite you to include your use cases and +1s there for visibility. Thank you!

**Comment by AnithaYerra** [comment]
It works with those 3 commands  what ever you mentioned but i can see i couldnt able to click on deleteSelected option in datastore view - 
![image](https://user-images.githubusercontent.com/36034375/203786229-fbbf5bbb-307a-473b-b4f0-8302f0a40396.png) Its disabled. May I know how can i make this to work

**Comment by remko** [comment]
@AnithaYerra Try https://github.com/remko/dsadmin This is one of the many reasons I created it: because most of the other UIs had problems, including the 'delete not working' you're describing.

**Comment by meredithslota** [comment]
The supported Emulator Suite (https://firebase.google.com/docs/emulator-suite) does not specify Datastore support at this time — though there is a Datastore emulator (https://cloud.google.com/datastore/docs/tools/datastore-emulator), the full UI support appears currently limited to Firestore/Firebase. I will see if I can find out of this is intentional/official.

**Comment by meredithslota** [comment]
Hi folks — I've managed to track down an existing internal feature request for this and have added the original request + some additional context to the issue: https://issuetracker.google.com/131922340 I'm going to close this out in favor of that one, to de-dupe. Please follow along there!
