### ISSUE TITLE
Are we wrapping concurrent transaction errors inside plain DatastoreExceptions?

### ISSUE THREAD

**Issue by wsh** [googleapis/google-cloud-datastore#191]
[This post](https://medium.com/@jon_gille/are-you-kidding-me-google-663dacaea9) suggests we might be.

**Comment by eddavisson** [comment]
I got really confused about the wrapped exceptions in that post and then noticed they are different types:

The outer type is:
`com.google.cloud.datastore.DatastoreException`

The cause type is:
`com.google.datastore.v1.client.DatastoreException`

The fact that we don't have specific types for specific error codes is debatable, but it's at least working as designed. The surprising parts for me are:

1. `INVALID_ARGUMENT` rather than `ALREADY_EXISTS`. We changed this specific behavior with the v1 launch. https://cloud.google.com/datastore/release-notes#august_16_2016.
2. `ABORTED` on the cause exception becoming `OK` on the outer exception.

**Comment by wsh** [comment]
The specific types for specific error codes thing [may be fixed by GAPIC migration](http://googleapis.github.io/gax-java/1.16.0/apidocs/com/google/api/gax/rpc/ApiException.html). :slightly_smiling_face:

I'm hoping to know more about the operation so that I can dig into 1. 2 sounds like a bug for google-cloud-java.

**Comment by wsh** [comment]
With respect to 1, I wonder if the author is using v1beta3. We return `INVALID_ARGUMENT` for that one and, indeed, `ALREADY_EXISTS` for v1.

**Comment by jgille** [comment]
Hi, author of the rant here. Getting INVALID_ARGUMENT when adding the same entity twice is an emulator bug, running towards the real Datastore service I get code 6 and reason ALREADY_EXISTS just as expected.

I ran the emulator as a Docker container (google/cloud-sdk:183.0.0).

The other weird behavior (getting code=0 and reason=null when concurrently modifying an entity in transactions) is still there with the real thing though.

**Comment by wsh** [comment]
The emulator behavior has been fixed with the newest release (1.4.0). The other question remains.

**Comment by fabriziodemaria** [comment]
```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-datastore</artifactId>
    <version>1.16.0</version>
</dependency>
```

Using the Java library above (latest version) the erroneous emulator behaviour persists: trying to add an already existing entity (via a transaction, with a direct call to `Transaction.commit()`) throws a `DatastoreException` with reason `INVALID_ARGUMENT`, while the same operation on a real Datastore throws an exception with reason `ALREADY_EXISTS`.
Is the fix supposed to be rolled out on a future version of the Java client?

@wsh

**Comment by meredithslota** [comment]
If you are still experiencing issues with the java-datastore client, please file them here: https://github.com/googleapis/java-datastore/issues Thank you!
