### ISSUE TITLE
Is the emulator intended to support happy-path testing only?

### ISSUE THREAD

**Issue by nickform** [googleapis/google-cloud-datastore#212]
I'm getting the impression from ~20 minutes of searching for ways to configure the emulator behaviour for a given test that the emulator's prime use case is testing happy paths. Can anyone confirm or deny this. If denying a link to the documentation I've been looking for would be much appreciated.

I also have the same question about the pubsub emulator in case anyone answering happens to oversight over both.

**Comment by anguillanneuf** [comment]
@nickform Thank you for your patience. We document the limitations of both the DataStore and Pub/Sub emulators (See "Known issues" or "Known limitations" sections).  Because the emulators are not open source, they won't be able to support all test cases. In that sense, you can say that the prime use case for them is testing the happy paths. If you'd like to request a feature and tell us why it is important to you, please let us know again. Below are the links to the documentation:

DataStore:

- https://cloud.google.com/datastore/docs/tools/datastore-emulator
- https://cloud.google.com/datastore/docs/tools/emulator-export-import

Pub/Sub

- https://cloud.google.com/pubsub/docs/emulator
